repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]

- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.6.0-1
  hooks:
    - id: shfmt
      name: Format shell scripts

- repo: https://github.com/jvstein/pre-commit-dotnet-format
  rev: 'v0.2'
  hooks:
  - id: dotnet-format
    name: Format lib project
    args: ['src/SpaceBattle/space-battle.csproj']

  - id: dotnet-format
    name: Format tests project
    args: ['src/SpaceBattleTests/tests.csproj']

  - id: dotnet-format
    name: Format gRPC service project
    args: ['src/SpaceBattleGrpc/SpaceBattleGrpc.csproj']
